Campaign promotion
properweb/Bazar_Repo pull request #11
Opened 2023-01-30 06:21 UTC by arijit1111

2023-01-30 17:15 UTC, SonaKhachatryan1995 reviewed
Most common and most serious issue it that there is not [authorization](https://laravel.com/docs/9.x/authorization) implemented.Implement authorization for each controller method via [ policies](https://laravel.com/docs/9.x/authorization#writing-policies)

Remove fallowing files and folders because we are not using them and they are creating additional noise
    Modules/Campaign/Config/.gitkeep
    Modules/Campaign/Console
    Modules/Campaign/Database
    Modules/Campaign/Entities/.gitkeep
    Modules/Campaign/Http/Middleware
    Modules/Campaign/Http/Controllers/.gitkeep
    Modules/Campaign/Http/Requests/.gitkeep
    Modules/Campaign/Resources
    Modules/Campaign/Tests
    Modules/Campaign/package.json
    Modules/Campaign/vite.config.js

Not this is not the list of full files that need to be deleted, all .gitkeep files need to be deleted and if folder is empty it should be deleted as well. Basically, read module structure, understand do we need this file or not, if we don't need it then we are deleting it.'

Go over files and folders in Promotion Module as well.

How campaign table is created in db? Add migration to module.
For all service methods specifies argument types and return types.

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Entities/Campaign.php
> +namespace Modules\campaign\Entities;
Namespace is not correct, should be Modules\Campaign\Entities;

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Controllers/CampaignController.php
> +class CampaignController extends Controller {
{ should start from new line according to [PSR2 ](https://www.php-fig.org/psr/psr-2/)

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Controllers/CampaignController.php
> +    public function index(Request $request) {
{ should start from new line according to [PSR2](https://www.php-fig.org/psr/psr-2/)

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Controllers/CampaignController.php
> +    public function store(StoreCampaignRequest $request) {
{ should start from new line according to [PSR2](https://www.php-fig.org/psr/psr-2/)

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Controllers/CampaignController.php
> +    public function show($campaignKey) {
{ should start from new line according to [PSR2](https://www.php-fig.org/psr/psr-2/)

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Controllers/CampaignController.php
> +    public function update(Request $request, $campaignKey) {
Empty method should be deleted

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Controllers/CampaignController.php
> +    /**
Comment message is not descriptive and not according to PHPDoc

Better something like this

    /**
     * Get list of campaigns
     *
     * @param  Request  $request
     * @return \Illuminate\Http\JsonResponse
     */
     
     we are not displaying anything we are returning json, that's why it's better to say "get" and the "resource" in our  case is "campaign" so be specific about that as well.  Leave a line between message and parameter list

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Controllers/CampaignController.php
> +    /**
comment message is not descriptive and not according to PHPDoc

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Controllers/CampaignController.php
> +        if ($campaign) {
Add line before "if" statement

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Controllers/CampaignController.php
> +        return response()->json($response);
Add line before return statement

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Controllers/CampaignController.php
> +     * Remove the specified resource from storage.
comment message is not descriptive and not according to PHPDoc

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Controllers/CampaignController.php
> +    public function destroy(Request $request, $campaignKey) {
remove Request $request it's unused variable

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Services/CampaignService.php
> +        $campaign->brand_id = $campaignData['user_id'];
!!!! MPORTANT: Security issue

$campaignData['user_id'] is not validated in request and if instead of my id I'll send some other users Id I can create campaign in their behalf

Besides brand_id = user_id does not make any sence, variable names should be consistent

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Services/CampaignService.php
> +        try {
We don't need db transaction here as we are performing multiple DB manipulations.

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Services/CampaignService.php
> +        try {
We don't need try/catch in this particular case

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Controllers/CampaignController.php
> +        $response = $this->campaignService->store($request->all());
Should be $request->validated() not $request->all()

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Services/CampaignService.php
> +     * Save order
Comment is not descriptive and not containing write parameters list, and also not according to PhpDoc standard

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Services/CampaignService.php
> +    /**
Comment is not descriptive and not containing write parameters list, and also not according to PhpDoc standard

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Services/CampaignService.php
> +        $user = User::find($requestData->user_id);
!!! IMPORTANT containes security issue

If I'll send some random user ID will get data from here.

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Services/CampaignService.php
> +        if ($user) {
Code should be refactored like this 

        $user = User::find($requestData->user_id);

        if (!$user) {
        //return no data message
        }
       //

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Services/CampaignService.php
> +            switch ($status) {
replace switch with if

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Services/CampaignService.php
> +    public function delete( $campaignKey):
syntax error

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Services/CampaignService.php
> +    {
Refactor function completely, we don;t need try catch or transaction here. also deleteCampaign is unnecessary function

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Services/CampaignService.php
> +    /**
Delete the whole function we don't need it, place whole logic in "delete" method

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Requests/StoreCampaignRequest.php
> +        return [
missing validation for user_id

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Controllers/CampaignController.php
> +<?php
Missing authorization in all methods

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Routes/api.php
> +Route::prefix('campaigns')->group(function () {
add route[ naming ](https://laravel.com/docs/9.x/routing#named-routes)

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Entities/Promotion.php
> +class Promotion extends Model {
{ should start from new line according to [PSR2](https://www.php-fig.org/psr/psr-2/)

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Controllers/PromotionController.php
> +class PromotionController extends Controller {
{ should start from new line according to [PSR2](https://www.php-fig.org/psr/psr-2/)

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Controllers/PromotionController.php
> +use Modules\User\Entities\User;
Unused statement

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Controllers/PromotionController.php
> +use Modules\Brand\Entities\Brand;
Unused statement

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Controllers/PromotionController.php
> +    public function index(Request $request) {
{ should start from new line according to [PSR2](https://www.php-fig.org/psr/psr-2/)

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Controllers/PromotionController.php
> +    public function store(StorePromotionRequest $request) {
{ should start from new line according to [PSR2](https://www.php-fig.org/psr/psr-2/)

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Controllers/PromotionController.php
> +    public function show(Request $request, $promotionKey) {
{ should start from new line according to [PSR2](https://www.php-fig.org/psr/psr-2/)

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Controllers/PromotionController.php
> +    public function update(Request $request, $promotionKey) {
Delete the function it's not used

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Controllers/PromotionController.php
> +    public function destroy(Request $request, $promotionKey) {
{ should start from new line according to [PSR2](https://www.php-fig.org/psr/psr-2/)

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Controllers/PromotionController.php
> +    public function destroy(Request $request, $promotionKey) {
Move to service method

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Controllers/PromotionController.php
> +        $promotion = Promotion::where('promotion_key', $promotionKey)->first();
this line and next line can be combined

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Controllers/PromotionController.php
> +     * Store a newly created resource in storage.
Comments is not descriptive and contains errors, add space between description and parameter list

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Controllers/PromotionController.php
> +     * Show the specified resource.
Comments is not descriptive and contains errors, add space between description and parameter list

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Controllers/PromotionController.php
> +    /**
Comments is not descriptive and contains errors, add space between description and parameter list

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Requests/StorePromotionRequest.php
> +        return [
Promotion contains a lot of fields but we are validating only title, all other fields should pass according validation as well

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Controllers/PromotionController.php
> +        $response = $this->promotionService->store($request->all());
this should not be $request->all() it should be $request->validated()

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Services/PromotionService.php
> +use Illuminate\Support\Str;
unnecessary use statement

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Services/PromotionService.php
> +        DB::beginTransaction();
no need fro transaction and try/catch

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Services/PromotionService.php
> +        $user = User::find($requestData->user_id);
!!! IMPORTANT contains security vulnerability

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Services/PromotionService.php
> +            switch ($status) {
change switch to if

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Services/PromotionService.php
> +        if ($user) {
Refactor
    $user = User::find($requestData->user_id);

    if (!$user) {
    //return no data message
    }
   // code goes here

2023-01-30 17:15 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Routes/api.php
> +Route::prefix('promotions')->group(function () {
Add route naming

2023-02-04 15:28 UTC, SonaKhachatryan1995 commented
> Most common and most serious issue it that there is not [authorization](https://laravel.com/docs/9.x/authorization) implemented.Implement authorization for each controller method via [ policies](https://laravel.com/docs/9.x/authorization#writing-policies)
> 
> Remove fallowing files and folders because we are not using them and they are creating additional noise Modules/Campaign/Config/.gitkeep Modules/Campaign/Console Modules/Campaign/Database Modules/Campaign/Entities/.gitkeep Modules/Campaign/Http/Middleware Modules/Campaign/Http/Controllers/.gitkeep Modules/Campaign/Http/Requests/.gitkeep Modules/Campaign/Resources Modules/Campaign/Tests Modules/Campaign/package.json Modules/Campaign/vite.config.js
> 
> Not this is not the list of full files that need to be deleted, all .gitkeep files need to be deleted and if folder is empty it should be deleted as well. Basically, read module structure, understand do we need this file or not, if we don't need it then we are deleting it.'
> 
> Go over files and folders in Promotion Module as well.
> 
> How campaign table is created in db? Add migration to module. For all service methods specifies argument types and return types.

2023-02-04 15:35 UTC, SonaKhachatryan1995 reviewed
**IMPORTANT** Add authorization for all controller methods with [Laravel policies](https://laravel.com/docs/9.x/authorization)

Make sure to delete all unnecessary .gitkeep fiels.
Add route names.
Validate input data properly.
Specify function input and return type parameter correctly and check that PHPDoc is formed correct as well.

2023-02-04 15:35 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Services/CampaignService.php
> +    public function delete($campaignKey): void
return type declaration is not correct

2023-02-04 15:35 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Services/PromotionService.php
> +        if(!empty($promotionData['products'])){
Empty "if"statement remove

2023-02-04 15:35 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Services/PromotionService.php
> +        $productsStr = '';
Unnecessary variable

2023-02-04 15:35 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Services/PromotionService.php
> +     * update promotion
Comment should start with capital letter

2023-02-04 15:35 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Services/PromotionService.php
> +    {
unnecessary transaction

2023-02-04 15:35 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Services/PromotionService.php
> +            $productsStr = '';
unused variable

2023-02-04 15:35 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Services/PromotionService.php
> +            if(!empty($requestData['products'])){
empty if statement

2023-02-04 15:35 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Services/PromotionService.php
> +        try {
unnecessary try-catch statement

2023-02-04 15:35 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Services/PromotionService.php
> +    public function updatePromotion(array $promotionData, Promotion $promotion): Promotion
unnecessary function, can call update directly from controller

2023-02-11 15:43 UTC, arijit1111 commented
> 
Authorization for campaign controller method via policies

Removed unused  and empty files and folder from Campaign Module

Migration to module will be done on next push.

For all service methods  of Campaign argument types and return types are specified using PHPstorm cleanup and rearrange

2023-02-11 15:47 UTC, arijit1111 commented
> **IMPORTANT** Add authorization for all controller methods with [Laravel policies](https://laravel.com/docs/9.x/authorization)
> 
> Make sure to delete all unnecessary .gitkeep fiels. Add route names. Validate input data properly. Specify function input and return type parameter correctly and check that PHPDoc is formed correct as well.

1. Authorization for campaign controller method via policies & Authentication via Sanctum. So we have implemented security on both ways
2. PHPdoc corrections done, function input and return type parameter correctly specified, Input data validated properly using rules

2023-02-13 08:18 UTC, SonaKhachatryan1995 requested changes
Remove Modules/Campaign/Providers/.gitkeep file

2023-02-13 08:18 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Services/CampaignService.php
> +use Illuminate\Support\Facades\Auth;
Unused "use" statement, also the line above

2023-02-13 08:18 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Services/CampaignService.php
> +        if ($user->cannot('create', Campaign::class)) {
Authorization should be done in controller.

2023-02-13 08:18 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Services/CampaignService.php
> +        if ($user->cannot('viewAny', Campaign::class)) {
Authorization should be done in controller

2023-02-13 08:18 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Services/CampaignService.php
> +        if ($user->cannot('delete', $campaign)) {
Authorization should be done in controller

2023-02-13 08:18 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Policies/CampaignPolicy.php
> +        return $user->role === 'brand';
Instead of using string "brand" define constant("ROLE_BRAND" ) in User Entity and use constant.

2023-02-13 08:18 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Policies/CampaignPolicy.php
> +        return $user->id === $campaign->user_id;
in order to not repeat ourselves it's better to create "protected function access" store this logic there and call access function in view, edit, delete etc methods.

2023-02-13 08:18 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Policies/CampaignPolicy.php
> +        return $user->role === 'brand';
Instead of using string "brand" define constant("ROLE_BRAND" ) in User Entity and use constant.

2023-02-13 08:18 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Entities/Campaign.php
> +    const CAMPAIGN_STATUS = 'draft';
Better to name status as `const STATUS_DRAFT = 'draft'`. This way we will have more flexibility for new statuses.let say if we need status active we can name it `const STATUS_ACTIVE = 'active'`

2023-02-13 08:18 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Requests/StoreCampaignRequest.php
> +            'user_id' => 'nullable|integer',
Check that user exists in users table.

2023-02-13 08:18 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Http/Requests/StoreCampaignRequest.php
> +            'campaign_key' => 'nullable|string',
campaign_key is auto-generated, so no need to validate it here

2023-02-13 08:18 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Routes/api.php
> +Route::middleware('auth:sanctum')->group(function () {
Add naming for all routes

2023-02-13 14:56 UTC, arijit1111 commented
Authorization done in controller
added protected class to avoid repeated code
and changes according feedback

2023-02-14 17:10 UTC, SonaKhachatryan1995 reviewed
There are unnecessary "use" statements.
Make sure to include classes with "use" statement when using them in controllers or services.

2023-02-15 15:51 UTC, arijit1111 commented
Authorization for promotion controller method via policies
Authentication via Sanctum in controller
Removed unused and empty files and folder from Promotion Module

2023-02-15 16:35 UTC, SonaKhachatryan1995 requested changes
In `PromotionServcie->store` method comment is not correct.
In `PromotionServcie->createPromotion` method we don't need first `$promotion->save();`
In `PromotionServcie->update`  method we don't need $user = User::find($requestData['user_id']);

2023-02-15 16:35 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Entities/Promotion.php
> +use Illuminate\Support\Facades\DB;
Unnecessary "use" statement, remove

2023-02-15 16:35 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Controllers/PromotionController.php
> +//use Modules\Promotion\Http\Requests\UpdatePromotionRequest;
Uncomment the line

2023-02-15 16:35 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Controllers/PromotionController.php
> +
Remove line

2023-02-15 16:35 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Controllers/PromotionController.php
> +use Illuminate\Http\Request;
Remove 
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
we are not using them

2023-02-15 16:35 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Http/Services/PromotionService.php
>  use Illuminate\Support\Facades\DB;
Remove, not used

2023-02-15 16:35 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Routes/api.php
> +Route::middleware('auth:sanctum')->group(function () {
Add naming for the routes

2023-02-16 18:21 UTC, SonaKhachatryan1995 requested changes
Migrations are not working

2023-02-16 18:21 UTC, SonaKhachatryan1995 commented on Modules/Campaign/Database/Migrations/2023_02_16_143538_create_campaigns_table.php
> +            $table->foreign('user_id')->references('id')->on('users')->onDelete('CASCADE');
Foreign key declaration should come after timestamps and be separated with line.

2023-02-16 18:21 UTC, SonaKhachatryan1995 commented on Modules/Promotion/Database/Migrations/2023_02_16_143620_create_promotions_table.php
> +            $table->foreign('user_id')->references('id')->on('users')->onDelete('CASCADE');
Foreign key declaration should come after timestamps and be separated with line

2023-02-27 18:11 UTC, SonaKhachatryan1995 approved these changes

2023-02-27 18:11 UTC, merged