Country Feature Commit
properweb/Bazar_Repo pull request #28
Opened 2023-04-04 14:31 UTC by arijit1111

Pull request generated for Module Country

2023-04-05 08:18 UTC, SonaKhachatryan1995 requested changes
Remove use ```Illuminate\Database\Eloquent\Factory; ``` from ```CountryServiceProvider.php```

2023-04-05 08:18 UTC, SonaKhachatryan1995 commented on Modules/Country/Entities/City.php
> +    protected $fillable = [];
Add fillables

2023-04-05 08:18 UTC, SonaKhachatryan1995 commented on Modules/Country/Entities/Country.php
> +
add fillables

2023-04-05 08:18 UTC, SonaKhachatryan1995 commented on Modules/Country/Entities/State.php
> +    protected $fillable = [];
Add fillables

2023-04-05 08:18 UTC, SonaKhachatryan1995 commented on Modules/Country/Http/Controllers/CountryController.php
>  use Illuminate\Http\Request;
Remove this, not used

2023-04-05 08:18 UTC, SonaKhachatryan1995 commented on Modules/Country/Http/Requests/CityRequest.php
> +            'state_id' => 'required|integer'
Check if exists in state table

2023-04-05 08:18 UTC, SonaKhachatryan1995 commented on Modules/Country/Http/Requests/StateRequest.php
> +            'country_id' => 'required|integer'
Check if exists in countries table

2023-04-05 11:23 UTC, arijit1111 commented on Modules/Country/Entities/City.php
> +    protected $fillable = [];
Done

2023-04-05 11:23 UTC, arijit1111 commented on Modules/Country/Entities/Country.php
> +
Done

2023-04-05 11:23 UTC, arijit1111 commented on Modules/Country/Entities/State.php
> +    protected $fillable = [];
Done

2023-04-05 11:23 UTC, arijit1111 commented on Modules/Country/Http/Controllers/CountryController.php
>  use Illuminate\Http\Request;
Done

2023-04-05 11:23 UTC, arijit1111 commented on Modules/Country/Http/Requests/CityRequest.php
> +            'state_id' => 'required|integer'
Done

2023-04-05 11:23 UTC, arijit1111 commented on Modules/Country/Http/Requests/StateRequest.php
> +            'country_id' => 'required|integer'
Done

2023-04-05 11:24 UTC, arijit1111 commented
> 



> Remove use `Illuminate\Database\Eloquent\Factory; ` from `CountryServiceProvider.php`

Done

2023-04-06 12:10 UTC, SonaKhachatryan1995 approved these changes

2023-04-06 12:10 UTC, merged