Product management
properweb/Bazar_Repo pull request #3
Opened 2022-11-23 11:14 UTC by arijit1111

2022-11-25 13:01 UTC, shoaibrehman commented on Modules/Product/Http/Controllers/ProductController.php
> +                    if (isset($swatch_image) && $swatch_image != "" && filter_var($swatch_image, FILTER_VALIDATE_URL) === false) {
Replace ` $swatch_image != ""` with `!empty(swatch_image)`

2022-11-25 13:01 UTC, shoaibrehman commented on Modules/Product/Http/Controllers/ProductController.php
> +                case 1:
`case 1:` has the same code block as `default:`. Please remove `case 1:`

2022-11-25 13:01 UTC, shoaibrehman commented on Modules/Product/Http/Controllers/ProductController.php
> +use Illuminate\Contracts\Support\Renderable;
`use Illuminate\Contracts\Support\Renderable;` is not used anywhere in the file. Please remove.

2022-11-25 13:01 UTC, shoaibrehman commented on Modules/Product/Http/Controllers/ProductController.php
> +        $folderPath = public_path() . $vndr_upload_path;
`$folderPath` & `product_images` aren't used anywhere. Please remove.

2022-11-25 13:01 UTC, shoaibrehman commented on Modules/Product/Http/Controllers/ProductController.php
> +        $redis = Redis::connection();
Duplicate declaration. You have already defined `$redis` on line 293.

2022-11-25 14:12 UTC, arijit1111 commented on Modules/Product/Http/Controllers/ProductController.php
> +                    if (isset($swatch_image) && $swatch_image != "" && filter_var($swatch_image, FILTER_VALIDATE_URL) === false) {
Done

2022-11-25 14:12 UTC, arijit1111 commented on Modules/Product/Http/Controllers/ProductController.php
> +                case 1:
Done

2022-11-25 14:12 UTC, arijit1111 commented on Modules/Product/Http/Controllers/ProductController.php
> +use Illuminate\Contracts\Support\Renderable;
Done

2022-11-25 14:12 UTC, arijit1111 commented on Modules/Product/Http/Controllers/ProductController.php
> +        $folderPath = public_path() . $vndr_upload_path;
Done

2022-11-25 14:13 UTC, arijit1111 commented on Modules/Product/Http/Controllers/ProductController.php
> +        $redis = Redis::connection();
Done

2022-11-30 11:11 UTC, shoaibrehman commented on Modules/Product/Http/Controllers/ProductController.php
> +                    //$query->orderByRaw("TIME(updated_at) DESC");
Remove commented code.

2022-11-30 11:42 UTC, shoaibrehman requested changes

2022-11-30 11:42 UTC, shoaibrehman commented on Modules/Product/Http/Controllers/ProductController.php
> +            $product_variations_tbl = DB::raw("(SELECT product_id,id as variant_id,value1,value2,value3,sku as vsku,stock as vstock,image as vimage
Raw DB query needs to be replaced.

2022-11-30 11:42 UTC, shoaibrehman commented on Modules/Product/Http/Controllers/ProductController.php
> +    public function ImportShopify(Request $request)
Shopify functionality should be created in its own module to make the functionality modular. This is not the right approach.

2023-01-09 12:00 UTC, closed without merging