Commits for custom website
properweb/Bazar_Repo pull request #39
Opened 2023-05-31 08:31 UTC by arijit1111

Add API details 
Import Custom website
Update stock from custom website
Fetch custom website information

2023-06-01 19:00 UTC, smaqeelkazmi requested changes
I have made a comment for duplicate route, kindly check. After that we are good to merge @arijit1111

2023-06-01 19:00 UTC, smaqeelkazmi commented on Modules/Custom/Routes/api.php
> +        Route::post('/import-product', 'CustomController@importProduct')->name('importProduct');
@arijit1111 The route `import-product` and `add-api` have same business logic, why we created two separate?

2023-06-02 07:11 UTC, arijit1111 commented on Modules/Custom/Routes/api.php
> +        Route::post('/import-product', 'CustomController@importProduct')->name('importProduct');
No this not same routes.
For import-product routes to upload product excelsheet from custom webste.
For add-api routes to add api information of custom website like API URL, API KEY and API PASSWORD

2023-06-02 07:20 UTC, smaqeelkazmi approved these changes
PR approved

2023-06-02 07:20 UTC, merged