retailer order section
properweb/Bazar_Repo pull request #5
Opened 2022-12-23 14:21 UTC by arijit1111

retailer orders

2022-12-23 14:21 UTC, properweb commented
Task linked: [CU-85zrgkctf Orders Section](https://app.clickup.com/t/85zrgkctf)

2022-12-23 14:46 UTC, shoaibrehman requested changes

2022-12-23 14:46 UTC, shoaibrehman commented on Modules/Retailer/Http/Controllers/RetailerController.php
> +//        echo '<pre>';
Remove commented out code.

2022-12-23 14:46 UTC, shoaibrehman commented on Modules/Retailer/Http/Controllers/RetailerController.php
> +//        return $request->all();
Remove commented out code.

2023-01-06 11:32 UTC, shoaibrehman approved these changes

2023-01-09 11:38 UTC, merged