Review Brand & Wishlist Controllers
properweb/Bazar_Repo pull request #9
Opened 2023-01-11 13:52 UTC by arijit1111

Review Brand & Wishlist Controllers

2023-01-11 13:52 UTC, properweb commented
Task linked: [CU-2yehr3e Customer Wishlist](https://app.clickup.com/t/2yehr3e)

2023-01-13 13:58 UTC, shoaibrehman requested changes

2023-01-13 13:58 UTC, shoaibrehman commented on Modules/Backend/Http/Controllers/VendorController.php
> +        exit;
what's the purpose of this echo? And, then the exit? 

If function is not required for execution then please remote it.

2023-01-13 13:58 UTC, shoaibrehman commented on Modules/Order/Http/Controllers/OrderController.php
>      public function store(Request $request)
phpdocs is still missing

2023-01-13 13:58 UTC, shoaibrehman commented on Modules/Order/Http/Controllers/OrderController.php
> +    public function index(Request $request)
phpdocs is still missing

2023-01-13 13:58 UTC, shoaibrehman commented on Modules/Order/Http/Controllers/OrderController.php
> +    public function show(Request $request, $orderNumber)
phpdocs is still missing

2023-01-13 13:58 UTC, shoaibrehman commented on Modules/Order/Http/Controllers/OrderController.php
> +    public function packingSlip(Request $request)
phpdocs is still missing

2023-01-13 13:58 UTC, shoaibrehman commented on Modules/Order/Http/Controllers/OrderController.php
> +    public function accept(Request $request)
phpdocs is still missing

2023-01-13 13:58 UTC, shoaibrehman commented on Modules/Order/Http/Controllers/OrderController.php
> +    public function changeDate(Request $request)
phpdocs is still missing

2023-01-13 13:58 UTC, shoaibrehman commented on Modules/Order/Http/Controllers/OrderController.php
> +    public function changeAddress(Request $request)
phpdocs is still missing

2023-01-13 13:58 UTC, shoaibrehman commented on Modules/Order/Http/Controllers/OrderController.php
> +    public function split(Request $request)
phpdocs is still missing

2023-01-13 13:58 UTC, shoaibrehman commented on Modules/Order/Http/Controllers/OrderController.php
> +    public function csv(Request $request)
phpdocs is still missing

2023-01-13 13:58 UTC, shoaibrehman commented on Modules/Order/Http/Controllers/OrderController.php
> +    private function syncExternal($prdct_arr, $brandId)
phpdocs is still missing

2023-02-27 18:25 UTC, closed without merging